### ISSUE TITLE
Missing GitHub credentials

### ISSUE THREAD

**Issue by applejag** [jadolg/klum#217]
I don't have a clear repro, but I believe it had to do with the repository getting moved from one owner to another.

The `UserSyncGithub` resource has a `Ready` condition like so:

```yaml
status:
  conditions:
  - lastUpdateTime: "2025-02-05T22:02:41Z"
    status: "True"
    type: Ready
```

But today is 2025-03-03.

I haven't double-checked your code base but it seems that it does not add the credentials back if it's already `Ready` or otherwise unchanged.

It would be good if it did a resync when restarting, and perhaps on a timer as well, instead of only on change.

When restarting I see logs like:

```logs
time="2025-03-03T03:04:20Z" level=info msg="Synchronizing credentials for myuser-myrepo"
```

but the credentials are still missing in the GitHub repo envs.
