### ISSUE TITLE
typos in deploy.yaml

### ISSUE THREAD

**Issue by Kobidav** [jadolg/klum#80]
Hello.
Looks you have typos in deploy.yaml file.

```
env:
    - name: CONTEXT_NAME
      value: mycluster
    - name: SERVER
      value: https://myserver.example.com:6443
    - name: NAMESPACE
      value: klum
```

SERVER key should be SERVER_NAME, or removed.

Is it possible to get server name automatically, e.g. from "kubectl cluster-info" ? 

Thank you!
